/* File: readrmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Fri May 29 07:43:23 2020
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *readr_error;
static PyObject *readr_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = readr_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = readr_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* read_part *********************************/
static char doc_f2py_rout_readr_readr_read_part[] = "\
read_part(repo,iout,cpu_list,mode,xlims,verbose,longint)\n\nWrapper for ``read_part``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iout : input int\n"
"cpu_list : input rank-1 array('i') with bounds (f2py_cpu_list_d0)\n"
"mode : input string(len=10)\n"
"xlims : input rank-1 array('d') with bounds (f2py_xlims_d0)\n"
"verbose : input int\n"
"longint : input int";
/* #declfortranroutine# */
static PyObject *f2py_rout_readr_readr_read_part(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,string,double*,int*,int*,int*,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  int *cpu_list = NULL;
  npy_intp cpu_list_Dims[1] = {-1};
  const int cpu_list_Rank = 1;
  PyArrayObject *capi_cpu_list_tmp = NULL;
  int capi_cpu_list_intent = 0;
  PyObject *cpu_list_capi = Py_None;
  string mode = NULL;
  int slen(mode);
  PyObject *mode_capi = Py_None;
  double *xlims = NULL;
  npy_intp xlims_Dims[1] = {-1};
  const int xlims_Rank = 1;
  PyArrayObject *capi_xlims_tmp = NULL;
  int capi_xlims_intent = 0;
  PyObject *xlims_capi = Py_None;
  int verbose = 0;
  PyObject *verbose_capi = Py_None;
  int longint = 0;
  PyObject *longint_capi = Py_None;
  int f2py_cpu_list_d0 = 0;
  int f2py_xlims_d0 = 0;
  static char *capi_kwlist[] = {"repo","iout","cpu_list","mode","xlims","verbose","longint",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOO:readr.readr.read_part",\
    capi_kwlist,&repo_capi,&iout_capi,&cpu_list_capi,&mode_capi,&xlims_capi,&verbose_capi,&longint_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xlims */
  ;
  capi_xlims_intent |= F2PY_INTENT_IN;
  capi_xlims_tmp = array_from_pyobj(NPY_DOUBLE,xlims_Dims,xlims_Rank,capi_xlims_intent,xlims_capi);
  if (capi_xlims_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(readr_error,"failed in converting 5th argument `xlims' of readr.readr.read_part to C/Fortran array" );
  } else {
    xlims = (double *)(PyArray_DATA(capi_xlims_tmp));

  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.read_part to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.read_part() 2nd argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable cpu_list */
  ;
  capi_cpu_list_intent |= F2PY_INTENT_IN;
  capi_cpu_list_tmp = array_from_pyobj(NPY_INT,cpu_list_Dims,cpu_list_Rank,capi_cpu_list_intent,cpu_list_capi);
  if (capi_cpu_list_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(readr_error,"failed in converting 3rd argument `cpu_list' of readr.readr.read_part to C/Fortran array" );
  } else {
    cpu_list = (int *)(PyArray_DATA(capi_cpu_list_tmp));

  /* Processing variable mode */
  slen(mode) = 10;
  f2py_success = string_from_pyobj(&mode,&slen(mode),"",mode_capi,"string_from_pyobj failed in converting 4th argument `mode' of readr.readr.read_part to C string");
  if (f2py_success) {
  /* Processing variable verbose */
    verbose = (int)PyObject_IsTrue(verbose_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable longint */
    longint = (int)PyObject_IsTrue(longint_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable f2py_cpu_list_d0 */
  f2py_cpu_list_d0 = shape(cpu_list, 0);
  /* Processing variable f2py_xlims_d0 */
  f2py_xlims_d0 = shape(xlims, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(repo,&iout,cpu_list,mode,xlims,&verbose,&longint,&f2py_cpu_list_d0,&f2py_xlims_d0,slen(repo),slen(mode));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_xlims_d0 */
  /* End of cleaning variable f2py_cpu_list_d0 */
  } /*if (f2py_success) of longint*/
  /* End of cleaning variable longint */
  } /*if (f2py_success) of verbose*/
  /* End of cleaning variable verbose */
    STRINGFREE(mode);
  }  /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  if((PyObject *)capi_cpu_list_tmp!=cpu_list_capi) {
    Py_XDECREF(capi_cpu_list_tmp); }
  }  /*if (capi_cpu_list_tmp == NULL) ... else of cpu_list*/
  /* End of cleaning variable cpu_list */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
  if((PyObject *)capi_xlims_tmp!=xlims_capi) {
    Py_XDECREF(capi_xlims_tmp); }
  }  /*if (capi_xlims_tmp == NULL) ... else of xlims*/
  /* End of cleaning variable xlims */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of read_part ******************************/

/******************************* read_sinkprop *******************************/
static char doc_f2py_rout_readr_readr_read_sinkprop[] = "\
read_sinkprop(repo,iprop,drag_part,mode)\n\nWrapper for ``read_sinkprop``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iprop : input int\n"
"drag_part : input int\n"
"mode : input string(len=10)";
/*  */
static PyObject *f2py_rout_readr_readr_read_sinkprop(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,string,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iprop = 0;
  PyObject *iprop_capi = Py_None;
  int drag_part = 0;
  PyObject *drag_part_capi = Py_None;
  string mode = NULL;
  int slen(mode);
  PyObject *mode_capi = Py_None;
  static char *capi_kwlist[] = {"repo","iprop","drag_part","mode",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:readr.readr.read_sinkprop",\
    capi_kwlist,&repo_capi,&iprop_capi,&drag_part_capi,&mode_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.read_sinkprop to C string");
  if (f2py_success) {
  /* Processing variable iprop */
    f2py_success = int_from_pyobj(&iprop,iprop_capi,"readr.readr.read_sinkprop() 2nd argument (iprop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable drag_part */
    drag_part = (int)PyObject_IsTrue(drag_part_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable mode */
  slen(mode) = 10;
  f2py_success = string_from_pyobj(&mode,&slen(mode),"",mode_capi,"string_from_pyobj failed in converting 4th argument `mode' of readr.readr.read_sinkprop to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(repo,&iprop,&drag_part,mode,slen(repo),slen(mode));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(mode);
  }  /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  } /*if (f2py_success) of drag_part*/
  /* End of cleaning variable drag_part */
  } /*if (f2py_success) of iprop*/
  /* End of cleaning variable iprop */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of read_sinkprop ****************************/

/********************************* read_sink *********************************/
static char doc_f2py_rout_readr_readr_read_sink[] = "\
read_sink(repo,iout,icpu,levelmin,nlevelmax)\n\nWrapper for ``read_sink``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iout : input int\n"
"icpu : input int\n"
"levelmin : input int\n"
"nlevelmax : input int";
/*  */
static PyObject *f2py_rout_readr_readr_read_sink(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  int icpu = 0;
  PyObject *icpu_capi = Py_None;
  int levelmin = 0;
  PyObject *levelmin_capi = Py_None;
  int nlevelmax = 0;
  PyObject *nlevelmax_capi = Py_None;
  static char *capi_kwlist[] = {"repo","iout","icpu","levelmin","nlevelmax",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO:readr.readr.read_sink",\
    capi_kwlist,&repo_capi,&iout_capi,&icpu_capi,&levelmin_capi,&nlevelmax_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.read_sink to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.read_sink() 2nd argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable icpu */
    f2py_success = int_from_pyobj(&icpu,icpu_capi,"readr.readr.read_sink() 3rd argument (icpu) can't be converted to int");
  if (f2py_success) {
  /* Processing variable levelmin */
    f2py_success = int_from_pyobj(&levelmin,levelmin_capi,"readr.readr.read_sink() 4th argument (levelmin) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nlevelmax */
    f2py_success = int_from_pyobj(&nlevelmax,nlevelmax_capi,"readr.readr.read_sink() 5th argument (nlevelmax) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(repo,&iout,&icpu,&levelmin,&nlevelmax,slen(repo));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of nlevelmax*/
  /* End of cleaning variable nlevelmax */
  } /*if (f2py_success) of levelmin*/
  /* End of cleaning variable levelmin */
  } /*if (f2py_success) of icpu*/
  /* End of cleaning variable icpu */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of read_sink ******************************/

/*********************************** close ***********************************/
static char doc_f2py_rout_readr_readr_close[] = "\
close()\n\nWrapper for ``close``.\
\n";
/*  */
static PyObject *f2py_rout_readr_readr_close(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    ":readr.readr.close",\
    capi_kwlist))
    return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of close ********************************/

/********************************* skip_read *********************************/
static char doc_f2py_rout_readr_readr_skip_read[] = "\
skip_read(unit,nskip)\n\nWrapper for ``skip_read``.\
\n\nParameters\n----------\n"
"unit : input int\n"
"nskip : input int";
/*  */
static PyObject *f2py_rout_readr_readr_skip_read(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unit = 0;
  PyObject *unit_capi = Py_None;
  int nskip = 0;
  PyObject *nskip_capi = Py_None;
  static char *capi_kwlist[] = {"unit","nskip",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:readr.readr.skip_read",\
    capi_kwlist,&unit_capi,&nskip_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unit */
    f2py_success = int_from_pyobj(&unit,unit_capi,"readr.readr.skip_read() 1st argument (unit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nskip */
    f2py_success = int_from_pyobj(&nskip,nskip_capi,"readr.readr.skip_read() 2nd argument (nskip) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unit,&nskip);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of nskip*/
  /* End of cleaning variable nskip */
  } /*if (f2py_success) of unit*/
  /* End of cleaning variable unit */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of skip_read ******************************/

/********************************** charind **********************************/
static char doc_f2py_rout_readr_readr_charind[] = "\
charind = charind(iout)\n\nWrapper for ``charind``.\
\n\nParameters\n----------\n"
"iout : input int\n"
"\nReturns\n-------\n"
"charind : string(len=5)";
/* #declfortranroutine# */
static PyObject *f2py_rout_readr_readr_charind(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string charind = NULL;
  int slen(charind);
  PyObject *charind_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  static char *capi_kwlist[] = {"iout",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:readr.readr.charind",\
    capi_kwlist,&iout_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable charind */
  slen(charind) = 5;
  f2py_success = string_from_pyobj(&charind,&slen(charind),"",charind_capi,"string_from_pyobj failed in converting hidden `charind' of readr.readr.charind to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.charind() 1st argument (iout) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(charind,&iout,slen(charind));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("y",charind);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(charind);
  }  /*if (f2py_success) of charind*/
  /* End of cleaning variable charind */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of charind *******************************/

/******************************* part_filename *******************************/
static char doc_f2py_rout_readr_readr_part_filename[] = "\
part_filename = part_filename(repo,iout,icpu,mode)\n\nWrapper for ``part_filename``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iout : input int\n"
"icpu : input int\n"
"mode : input string(len=10)\n"
"\nReturns\n-------\n"
"part_filename : string(len=128)";
/* #declfortranroutine# */
static PyObject *f2py_rout_readr_readr_part_filename(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,int*,string,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string part_filename = NULL;
  int slen(part_filename);
  PyObject *part_filename_capi = Py_None;
  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  int icpu = 0;
  PyObject *icpu_capi = Py_None;
  string mode = NULL;
  int slen(mode);
  PyObject *mode_capi = Py_None;
  static char *capi_kwlist[] = {"repo","iout","icpu","mode",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:readr.readr.part_filename",\
    capi_kwlist,&repo_capi,&iout_capi,&icpu_capi,&mode_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable part_filename */
  slen(part_filename) = 128;
  f2py_success = string_from_pyobj(&part_filename,&slen(part_filename),"",part_filename_capi,"string_from_pyobj failed in converting hidden `part_filename' of readr.readr.part_filename to C string");
  if (f2py_success) {
  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.part_filename to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.part_filename() 2nd argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable icpu */
    f2py_success = int_from_pyobj(&icpu,icpu_capi,"readr.readr.part_filename() 3rd argument (icpu) can't be converted to int");
  if (f2py_success) {
  /* Processing variable mode */
  slen(mode) = 10;
  f2py_success = string_from_pyobj(&mode,&slen(mode),"",mode_capi,"string_from_pyobj failed in converting 4th argument `mode' of readr.readr.part_filename to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(part_filename,repo,&iout,&icpu,mode,slen(part_filename),slen(repo),slen(mode));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("y",part_filename);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(mode);
  }  /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  } /*if (f2py_success) of icpu*/
  /* End of cleaning variable icpu */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
    STRINGFREE(part_filename);
  }  /*if (f2py_success) of part_filename*/
  /* End of cleaning variable part_filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of part_filename ****************************/

/***************************** sinkprop_filename *****************************/
static char doc_f2py_rout_readr_readr_sinkprop_filename[] = "\
sinkprop_filename = sinkprop_filename(repo,iout)\n\nWrapper for ``sinkprop_filename``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iout : input int\n"
"\nReturns\n-------\n"
"sinkprop_filename : string(len=128)";
/* #declfortranroutine# */
static PyObject *f2py_rout_readr_readr_sinkprop_filename(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string sinkprop_filename = NULL;
  int slen(sinkprop_filename);
  PyObject *sinkprop_filename_capi = Py_None;
  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  static char *capi_kwlist[] = {"repo","iout",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:readr.readr.sinkprop_filename",\
    capi_kwlist,&repo_capi,&iout_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable sinkprop_filename */
  slen(sinkprop_filename) = 128;
  f2py_success = string_from_pyobj(&sinkprop_filename,&slen(sinkprop_filename),"",sinkprop_filename_capi,"string_from_pyobj failed in converting hidden `sinkprop_filename' of readr.readr.sinkprop_filename to C string");
  if (f2py_success) {
  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.sinkprop_filename to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.sinkprop_filename() 2nd argument (iout) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(sinkprop_filename,repo,&iout,slen(sinkprop_filename),slen(repo));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("y",sinkprop_filename);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
    STRINGFREE(sinkprop_filename);
  }  /*if (f2py_success) of sinkprop_filename*/
  /* End of cleaning variable sinkprop_filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************** end of sinkprop_filename **************************/

/******************************* sink_filename *******************************/
static char doc_f2py_rout_readr_readr_sink_filename[] = "\
sink_filename = sink_filename(repo,iout,icpu)\n\nWrapper for ``sink_filename``.\
\n\nParameters\n----------\n"
"repo : input string(len=128)\n"
"iout : input int\n"
"icpu : input int\n"
"\nReturns\n-------\n"
"sink_filename : string(len=128)";
/* #declfortranroutine# */
static PyObject *f2py_rout_readr_readr_sink_filename(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string sink_filename = NULL;
  int slen(sink_filename);
  PyObject *sink_filename_capi = Py_None;
  string repo = NULL;
  int slen(repo);
  PyObject *repo_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  int icpu = 0;
  PyObject *icpu_capi = Py_None;
  static char *capi_kwlist[] = {"repo","iout","icpu",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:readr.readr.sink_filename",\
    capi_kwlist,&repo_capi,&iout_capi,&icpu_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable sink_filename */
  slen(sink_filename) = 128;
  f2py_success = string_from_pyobj(&sink_filename,&slen(sink_filename),"",sink_filename_capi,"string_from_pyobj failed in converting hidden `sink_filename' of readr.readr.sink_filename to C string");
  if (f2py_success) {
  /* Processing variable repo */
  slen(repo) = 128;
  f2py_success = string_from_pyobj(&repo,&slen(repo),"",repo_capi,"string_from_pyobj failed in converting 1st argument `repo' of readr.readr.sink_filename to C string");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"readr.readr.sink_filename() 2nd argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable icpu */
    f2py_success = int_from_pyobj(&icpu,icpu_capi,"readr.readr.sink_filename() 3rd argument (icpu) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(sink_filename,repo,&iout,&icpu,slen(sink_filename),slen(repo));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("y",sink_filename);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of icpu*/
  /* End of cleaning variable icpu */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    STRINGFREE(repo);
  }  /*if (f2py_success) of repo*/
  /* End of cleaning variable repo */
    STRINGFREE(sink_filename);
  }  /*if (f2py_success) of sink_filename*/
  /* End of cleaning variable sink_filename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of sink_filename ****************************/

/******************************** progress_bar ********************************/
static char doc_f2py_rout_readr_readr_progress_bar[] = "\
progress_bar(iteration,maximum)\n\nWrapper for ``progress_bar``.\
\n\nParameters\n----------\n"
"iteration : input int\n"
"maximum : input int";
/*  */
static PyObject *f2py_rout_readr_readr_progress_bar(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iteration = 0;
  PyObject *iteration_capi = Py_None;
  int maximum = 0;
  PyObject *maximum_capi = Py_None;
  static char *capi_kwlist[] = {"iteration","maximum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:readr.readr.progress_bar",\
    capi_kwlist,&iteration_capi,&maximum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iteration */
    f2py_success = int_from_pyobj(&iteration,iteration_capi,"readr.readr.progress_bar() 1st argument (iteration) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maximum */
    f2py_success = int_from_pyobj(&maximum,maximum_capi,"readr.readr.progress_bar() 2nd argument (maximum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&iteration,&maximum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of maximum*/
  /* End of cleaning variable maximum */
  } /*if (f2py_success) of iteration*/
  /* End of cleaning variable iteration */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of progress_bar ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_readr_def[] = {
  {"real_table",2,{{-1,-1}},NPY_DOUBLE},
  {"integer_table",2,{{-1,-1}},NPY_INT},
  {"long_table",2,{{-1,-1}},NPY_LONGLONG},
  {"byte_table",2,{{-1,-1}},NPY_BYTE},
  {"nhvar",0,{{-1}},NPY_INT},
  {"aexp",0,{{-1}},NPY_DOUBLE},
  {"read_part",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_read_part,doc_f2py_rout_readr_readr_read_part},
  {"read_sinkprop",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_read_sinkprop,doc_f2py_rout_readr_readr_read_sinkprop},
  {"read_sink",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_read_sink,doc_f2py_rout_readr_readr_read_sink},
  {"close",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_close,doc_f2py_rout_readr_readr_close},
  {"skip_read",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_skip_read,doc_f2py_rout_readr_readr_skip_read},
  {"charind",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_charind,doc_f2py_rout_readr_readr_charind},
  {"part_filename",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_part_filename,doc_f2py_rout_readr_readr_part_filename},
  {"sinkprop_filename",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_sinkprop_filename,doc_f2py_rout_readr_readr_sinkprop_filename},
  {"sink_filename",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_sink_filename,doc_f2py_rout_readr_readr_sink_filename},
  {"progress_bar",-1,{{-1}},0,NULL,(void *)f2py_rout_readr_readr_progress_bar,doc_f2py_rout_readr_readr_progress_bar},
  {NULL}
};

static void f2py_setup_readr(void (*real_table)(int*,int*,void(*)(char*,int*),int*),void (*integer_table)(int*,int*,void(*)(char*,int*),int*),void (*long_table)(int*,int*,void(*)(char*,int*),int*),void (*byte_table)(int*,int*,void(*)(char*,int*),int*),char *nhvar,char *aexp,char *read_part,char *read_sinkprop,char *read_sink,char *close,char *skip_read,char *charind,char *part_filename,char *sinkprop_filename,char *sink_filename,char *progress_bar) {
  int i_f2py=0;
  f2py_readr_def[i_f2py++].func = real_table;
  f2py_readr_def[i_f2py++].func = integer_table;
  f2py_readr_def[i_f2py++].func = long_table;
  f2py_readr_def[i_f2py++].func = byte_table;
  f2py_readr_def[i_f2py++].data = nhvar;
  f2py_readr_def[i_f2py++].data = aexp;
  f2py_readr_def[i_f2py++].data = read_part;
  f2py_readr_def[i_f2py++].data = read_sinkprop;
  f2py_readr_def[i_f2py++].data = read_sink;
  f2py_readr_def[i_f2py++].data = close;
  f2py_readr_def[i_f2py++].data = skip_read;
  f2py_readr_def[i_f2py++].data = charind;
  f2py_readr_def[i_f2py++].data = part_filename;
  f2py_readr_def[i_f2py++].data = sinkprop_filename;
  f2py_readr_def[i_f2py++].data = sink_filename;
  f2py_readr_def[i_f2py++].data = progress_bar;
}
extern void F_FUNC(f2pyinitreadr,F2PYINITREADR)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char*,char*,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_readr(void) {
  F_FUNC(f2pyinitreadr,F2PYINITREADR)(f2py_setup_readr);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "readr",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_readr(void) {
#else
#define RETVAL
PyMODINIT_FUNC initreadr(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = readr_module = PyModule_Create(&moduledef);
#else
  m = readr_module = Py_InitModule("readr", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module readr (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'readr' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  readr --- real_table,integer_table,long_table,byte_table,nhvar,aexp,read_part(),read_sinkprop(),read_sink(),close(),skip_read(),charind(),part_filename(),sinkprop_filename(),sink_filename(),progress_bar()"".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  readr_error = PyErr_NewException ("readr.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_readr_error", readr_error);
  Py_DECREF(readr_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }










/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "readr", PyFortranObject_New(f2py_readr_def,f2py_init_readr));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"readr");
#endif
  return RETVAL;
}
#ifdef __cplusplus
}
#endif
