/* File: a2cmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Apr 26 00:13:44 2016
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *a2c_error;
static PyObject *a2c_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    char errstring[256];\
    sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
    PyErr_SetString(a2c_error,errstring);\
    /*goto capi_fail;*/\
  } else 
#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = a2c_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = a2c_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = a2c_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(a2c_count,A2C_COUNT)(int*,int*,string,double*,double*,double*,double*,double*,double*,int*,size_t);
extern void F_FUNC_US(a2c_load,A2C_LOAD)(double*,double*,double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t);
extern void F_FUNC_US(a2c_load_shared,A2C_LOAD_SHARED)(double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t);
extern void F_FUNC(title,TITLE)(int*,string,size_t);
extern void F_FUNC(hilbert3d,HILBERT3D)(int*,int*,int*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* a2c_count *********************************/
static char doc_f2py_rout_a2c_a2c_count[] = "\
a2c_count(ngridtot,nvarh,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax)\n\nWrapper for ``a2c_count``.\
\n\nParameters\n----------\n"
"ngridtot : input int\n"
"nvarh : input int\n"
"repository : input string(len=-1)\n"
"xmin : input float\n"
"xmax : input float\n"
"ymin : input float\n"
"ymax : input float\n"
"zmin : input float\n"
"zmax : input float\n"
"lmax : input int";
/* extern void F_FUNC_US(a2c_count,A2C_COUNT)(int*,int*,string,double*,double*,double*,double*,double*,double*,int*,size_t); */
static PyObject *f2py_rout_a2c_a2c_count(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,string,double*,double*,double*,double*,double*,double*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int ngridtot = 0;
  PyObject *ngridtot_capi = Py_None;
  int nvarh = 0;
  PyObject *nvarh_capi = Py_None;
  string repository = NULL;
  int slen(repository);
  PyObject *repository_capi = Py_None;
  double xmin = 0;
  PyObject *xmin_capi = Py_None;
  double xmax = 0;
  PyObject *xmax_capi = Py_None;
  double ymin = 0;
  PyObject *ymin_capi = Py_None;
  double ymax = 0;
  PyObject *ymax_capi = Py_None;
  double zmin = 0;
  PyObject *zmin_capi = Py_None;
  double zmax = 0;
  PyObject *zmax_capi = Py_None;
  int lmax = 0;
  PyObject *lmax_capi = Py_None;
  static char *capi_kwlist[] = {"ngridtot","nvarh","repository","xmin","xmax","ymin","ymax","zmin","zmax","lmax",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO:a2c.a2c_count",\
    capi_kwlist,&ngridtot_capi,&nvarh_capi,&repository_capi,&xmin_capi,&xmax_capi,&ymin_capi,&ymax_capi,&zmin_capi,&zmax_capi,&lmax_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lmax */
    f2py_success = int_from_pyobj(&lmax,lmax_capi,"a2c.a2c_count() 10th argument (lmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ymax */
    f2py_success = double_from_pyobj(&ymax,ymax_capi,"a2c.a2c_count() 7th argument (ymax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nvarh */
    f2py_success = int_from_pyobj(&nvarh,nvarh_capi,"a2c.a2c_count() 2nd argument (nvarh) can't be converted to int");
  if (f2py_success) {
  /* Processing variable repository */
  slen(repository) = -1;
  f2py_success = string_from_pyobj(&repository,&slen(repository),"",repository_capi,"string_from_pyobj failed in converting 3rd argument `repository' of a2c.a2c_count to C string");
  if (f2py_success) {
  /* Processing variable zmin */
    f2py_success = double_from_pyobj(&zmin,zmin_capi,"a2c.a2c_count() 8th argument (zmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable zmax */
    f2py_success = double_from_pyobj(&zmax,zmax_capi,"a2c.a2c_count() 9th argument (zmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ymin */
    f2py_success = double_from_pyobj(&ymin,ymin_capi,"a2c.a2c_count() 6th argument (ymin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ngridtot */
    f2py_success = int_from_pyobj(&ngridtot,ngridtot_capi,"a2c.a2c_count() 1st argument (ngridtot) can't be converted to int");
  if (f2py_success) {
  /* Processing variable xmin */
    f2py_success = double_from_pyobj(&xmin,xmin_capi,"a2c.a2c_count() 4th argument (xmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xmax */
    f2py_success = double_from_pyobj(&xmax,xmax_capi,"a2c.a2c_count() 5th argument (xmax) can't be converted to double");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ngridtot,&nvarh,repository,&xmin,&xmax,&ymin,&ymax,&zmin,&zmax,&lmax,slen(repository));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of xmax*/
  /* End of cleaning variable xmax */
  } /*if (f2py_success) of xmin*/
  /* End of cleaning variable xmin */
  } /*if (f2py_success) of ngridtot*/
  /* End of cleaning variable ngridtot */
  } /*if (f2py_success) of ymin*/
  /* End of cleaning variable ymin */
  } /*if (f2py_success) of zmax*/
  /* End of cleaning variable zmax */
  } /*if (f2py_success) of zmin*/
  /* End of cleaning variable zmin */
    STRINGFREE(repository);
  }  /*if (f2py_success) of repository*/
  /* End of cleaning variable repository */
  } /*if (f2py_success) of nvarh*/
  /* End of cleaning variable nvarh */
  } /*if (f2py_success) of ymax*/
  /* End of cleaning variable ymax */
  } /*if (f2py_success) of lmax*/
  /* End of cleaning variable lmax */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of a2c_count ******************************/

/********************************** a2c_load **********************************/
static char doc_f2py_rout_a2c_a2c_load[] = "\
a2c_load(xarr,dxarr,varr,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax,[ngridtot,nvarh])\n\nWrapper for ``a2c_load``.\
\n\nParameters\n----------\n"
"xarr : input rank-2 array('d') with bounds (ngridtot,3)\n"
"dxarr : input rank-1 array('d') with bounds (ngridtot)\n"
"varr : input rank-2 array('d') with bounds (ngridtot,nvarh)\n"
"repository : input string(len=-1)\n"
"xmin : input float\n"
"xmax : input float\n"
"ymin : input float\n"
"ymax : input float\n"
"zmin : input float\n"
"zmax : input float\n"
"lmax : input int\n"
"\nOther Parameters\n----------------\n"
"ngridtot : input int, optional\n    Default: shape(xarr,0)\n"
"nvarh : input int, optional\n    Default: shape(varr,1)";
/* extern void F_FUNC_US(a2c_load,A2C_LOAD)(double*,double*,double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t); */
static PyObject *f2py_rout_a2c_a2c_load(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *xarr = NULL;
  npy_intp xarr_Dims[2] = {-1, -1};
  const int xarr_Rank = 2;
  PyArrayObject *capi_xarr_tmp = NULL;
  int capi_xarr_intent = 0;
  PyObject *xarr_capi = Py_None;
  double *dxarr = NULL;
  npy_intp dxarr_Dims[1] = {-1};
  const int dxarr_Rank = 1;
  PyArrayObject *capi_dxarr_tmp = NULL;
  int capi_dxarr_intent = 0;
  PyObject *dxarr_capi = Py_None;
  double *varr = NULL;
  npy_intp varr_Dims[2] = {-1, -1};
  const int varr_Rank = 2;
  PyArrayObject *capi_varr_tmp = NULL;
  int capi_varr_intent = 0;
  PyObject *varr_capi = Py_None;
  string repository = NULL;
  int slen(repository);
  PyObject *repository_capi = Py_None;
  double xmin = 0;
  PyObject *xmin_capi = Py_None;
  double xmax = 0;
  PyObject *xmax_capi = Py_None;
  double ymin = 0;
  PyObject *ymin_capi = Py_None;
  double ymax = 0;
  PyObject *ymax_capi = Py_None;
  double zmin = 0;
  PyObject *zmin_capi = Py_None;
  double zmax = 0;
  PyObject *zmax_capi = Py_None;
  int lmax = 0;
  PyObject *lmax_capi = Py_None;
  int ngridtot = 0;
  PyObject *ngridtot_capi = Py_None;
  int nvarh = 0;
  PyObject *nvarh_capi = Py_None;
  static char *capi_kwlist[] = {"xarr","dxarr","varr","repository","xmin","xmax","ymin","ymax","zmin","zmax","lmax","ngridtot","nvarh",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|OO:a2c.a2c_load",\
    capi_kwlist,&xarr_capi,&dxarr_capi,&varr_capi,&repository_capi,&xmin_capi,&xmax_capi,&ymin_capi,&ymax_capi,&zmin_capi,&zmax_capi,&lmax_capi,&ngridtot_capi,&nvarh_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lmax */
    f2py_success = int_from_pyobj(&lmax,lmax_capi,"a2c.a2c_load() 11st argument (lmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ymax */
    f2py_success = double_from_pyobj(&ymax,ymax_capi,"a2c.a2c_load() 8th argument (ymax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable repository */
  slen(repository) = -1;
  f2py_success = string_from_pyobj(&repository,&slen(repository),"",repository_capi,"string_from_pyobj failed in converting 4th argument `repository' of a2c.a2c_load to C string");
  if (f2py_success) {
  /* Processing variable zmin */
    f2py_success = double_from_pyobj(&zmin,zmin_capi,"a2c.a2c_load() 9th argument (zmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable zmax */
    f2py_success = double_from_pyobj(&zmax,zmax_capi,"a2c.a2c_load() 10th argument (zmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xarr */
  xarr_Dims[1]=3;
  capi_xarr_intent |= F2PY_INTENT_IN;
  capi_xarr_tmp = array_from_pyobj(NPY_DOUBLE,xarr_Dims,xarr_Rank,capi_xarr_intent,xarr_capi);
  if (capi_xarr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 1st argument `xarr' of a2c.a2c_load to C/Fortran array" );
  } else {
    xarr = (double *)(PyArray_DATA(capi_xarr_tmp));

  /* Processing variable ymin */
    f2py_success = double_from_pyobj(&ymin,ymin_capi,"a2c.a2c_load() 7th argument (ymin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xmax */
    f2py_success = double_from_pyobj(&xmax,xmax_capi,"a2c.a2c_load() 6th argument (xmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xmin */
    f2py_success = double_from_pyobj(&xmin,xmin_capi,"a2c.a2c_load() 5th argument (xmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ngridtot */
  if (ngridtot_capi == Py_None) ngridtot = shape(xarr,0); else
    f2py_success = int_from_pyobj(&ngridtot,ngridtot_capi,"a2c.a2c_load() 1st keyword (ngridtot) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(xarr,0)==ngridtot,"shape(xarr,0)==ngridtot","1st keyword ngridtot","a2c_load:ngridtot=%d",ngridtot) {
  /* Processing variable dxarr */
  dxarr_Dims[0]=ngridtot;
  capi_dxarr_intent |= F2PY_INTENT_IN;
  capi_dxarr_tmp = array_from_pyobj(NPY_DOUBLE,dxarr_Dims,dxarr_Rank,capi_dxarr_intent,dxarr_capi);
  if (capi_dxarr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 2nd argument `dxarr' of a2c.a2c_load to C/Fortran array" );
  } else {
    dxarr = (double *)(PyArray_DATA(capi_dxarr_tmp));

  /* Processing variable varr */
  varr_Dims[0]=ngridtot;
  capi_varr_intent |= F2PY_INTENT_IN;
  capi_varr_tmp = array_from_pyobj(NPY_DOUBLE,varr_Dims,varr_Rank,capi_varr_intent,varr_capi);
  if (capi_varr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 3rd argument `varr' of a2c.a2c_load to C/Fortran array" );
  } else {
    varr = (double *)(PyArray_DATA(capi_varr_tmp));

  /* Processing variable nvarh */
  if (nvarh_capi == Py_None) nvarh = shape(varr,1); else
    f2py_success = int_from_pyobj(&nvarh,nvarh_capi,"a2c.a2c_load() 2nd keyword (nvarh) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(varr,1)==nvarh,"shape(varr,1)==nvarh","2nd keyword nvarh","a2c_load:nvarh=%d",nvarh) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(xarr,dxarr,varr,repository,&xmin,&xmax,&ymin,&ymax,&zmin,&zmax,&lmax,&ngridtot,&nvarh,slen(repository));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(varr,1)==nvarh)*/
  } /*if (f2py_success) of nvarh*/
  /* End of cleaning variable nvarh */
  if((PyObject *)capi_varr_tmp!=varr_capi) {
    Py_XDECREF(capi_varr_tmp); }
  }  /*if (capi_varr_tmp == NULL) ... else of varr*/
  /* End of cleaning variable varr */
  if((PyObject *)capi_dxarr_tmp!=dxarr_capi) {
    Py_XDECREF(capi_dxarr_tmp); }
  }  /*if (capi_dxarr_tmp == NULL) ... else of dxarr*/
  /* End of cleaning variable dxarr */
  } /*CHECKSCALAR(shape(xarr,0)==ngridtot)*/
  } /*if (f2py_success) of ngridtot*/
  /* End of cleaning variable ngridtot */
  } /*if (f2py_success) of xmin*/
  /* End of cleaning variable xmin */
  } /*if (f2py_success) of xmax*/
  /* End of cleaning variable xmax */
  } /*if (f2py_success) of ymin*/
  /* End of cleaning variable ymin */
  if((PyObject *)capi_xarr_tmp!=xarr_capi) {
    Py_XDECREF(capi_xarr_tmp); }
  }  /*if (capi_xarr_tmp == NULL) ... else of xarr*/
  /* End of cleaning variable xarr */
  } /*if (f2py_success) of zmax*/
  /* End of cleaning variable zmax */
  } /*if (f2py_success) of zmin*/
  /* End of cleaning variable zmin */
    STRINGFREE(repository);
  }  /*if (f2py_success) of repository*/
  /* End of cleaning variable repository */
  } /*if (f2py_success) of ymax*/
  /* End of cleaning variable ymax */
  } /*if (f2py_success) of lmax*/
  /* End of cleaning variable lmax */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of a2c_load ******************************/

/****************************** a2c_load_shared ******************************/
static char doc_f2py_rout_a2c_a2c_load_shared[] = "\
a2c_load_shared(dataarr,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax,nvarh,[ngridtot])\n\nWrapper for ``a2c_load_shared``.\
\n\nParameters\n----------\n"
"dataarr : input rank-2 array('d') with bounds (ngridtot,10)\n"
"repository : input string(len=-1)\n"
"xmin : input float\n"
"xmax : input float\n"
"ymin : input float\n"
"ymax : input float\n"
"zmin : input float\n"
"zmax : input float\n"
"lmax : input int\n"
"nvarh : input int\n"
"\nOther Parameters\n----------------\n"
"ngridtot : input int, optional\n    Default: shape(dataarr,0)";
/* extern void F_FUNC_US(a2c_load_shared,A2C_LOAD_SHARED)(double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t); */
static PyObject *f2py_rout_a2c_a2c_load_shared(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double *dataarr = NULL;
  npy_intp dataarr_Dims[2] = {-1, -1};
  const int dataarr_Rank = 2;
  PyArrayObject *capi_dataarr_tmp = NULL;
  int capi_dataarr_intent = 0;
  PyObject *dataarr_capi = Py_None;
  string repository = NULL;
  int slen(repository);
  PyObject *repository_capi = Py_None;
  double xmin = 0;
  PyObject *xmin_capi = Py_None;
  double xmax = 0;
  PyObject *xmax_capi = Py_None;
  double ymin = 0;
  PyObject *ymin_capi = Py_None;
  double ymax = 0;
  PyObject *ymax_capi = Py_None;
  double zmin = 0;
  PyObject *zmin_capi = Py_None;
  double zmax = 0;
  PyObject *zmax_capi = Py_None;
  int lmax = 0;
  PyObject *lmax_capi = Py_None;
  int ngridtot = 0;
  PyObject *ngridtot_capi = Py_None;
  int nvarh = 0;
  PyObject *nvarh_capi = Py_None;
  static char *capi_kwlist[] = {"dataarr","repository","xmin","xmax","ymin","ymax","zmin","zmax","lmax","nvarh","ngridtot",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOO|O:a2c.a2c_load_shared",\
    capi_kwlist,&dataarr_capi,&repository_capi,&xmin_capi,&xmax_capi,&ymin_capi,&ymax_capi,&zmin_capi,&zmax_capi,&lmax_capi,&nvarh_capi,&ngridtot_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lmax */
    f2py_success = int_from_pyobj(&lmax,lmax_capi,"a2c.a2c_load_shared() 9th argument (lmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ymax */
    f2py_success = double_from_pyobj(&ymax,ymax_capi,"a2c.a2c_load_shared() 6th argument (ymax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dataarr */
  dataarr_Dims[1]=10;
  capi_dataarr_intent |= F2PY_INTENT_IN;
  capi_dataarr_tmp = array_from_pyobj(NPY_DOUBLE,dataarr_Dims,dataarr_Rank,capi_dataarr_intent,dataarr_capi);
  if (capi_dataarr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 1st argument `dataarr' of a2c.a2c_load_shared to C/Fortran array" );
  } else {
    dataarr = (double *)(PyArray_DATA(capi_dataarr_tmp));

  /* Processing variable nvarh */
    f2py_success = int_from_pyobj(&nvarh,nvarh_capi,"a2c.a2c_load_shared() 10th argument (nvarh) can't be converted to int");
  if (f2py_success) {
  /* Processing variable repository */
  slen(repository) = -1;
  f2py_success = string_from_pyobj(&repository,&slen(repository),"",repository_capi,"string_from_pyobj failed in converting 2nd argument `repository' of a2c.a2c_load_shared to C string");
  if (f2py_success) {
  /* Processing variable zmin */
    f2py_success = double_from_pyobj(&zmin,zmin_capi,"a2c.a2c_load_shared() 7th argument (zmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable zmax */
    f2py_success = double_from_pyobj(&zmax,zmax_capi,"a2c.a2c_load_shared() 8th argument (zmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ymin */
    f2py_success = double_from_pyobj(&ymin,ymin_capi,"a2c.a2c_load_shared() 5th argument (ymin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xmin */
    f2py_success = double_from_pyobj(&xmin,xmin_capi,"a2c.a2c_load_shared() 3rd argument (xmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable xmax */
    f2py_success = double_from_pyobj(&xmax,xmax_capi,"a2c.a2c_load_shared() 4th argument (xmax) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ngridtot */
  if (ngridtot_capi == Py_None) ngridtot = shape(dataarr,0); else
    f2py_success = int_from_pyobj(&ngridtot,ngridtot_capi,"a2c.a2c_load_shared() 1st keyword (ngridtot) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(dataarr,0)==ngridtot,"shape(dataarr,0)==ngridtot","1st keyword ngridtot","a2c_load_shared:ngridtot=%d",ngridtot) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(dataarr,repository,&xmin,&xmax,&ymin,&ymax,&zmin,&zmax,&lmax,&ngridtot,&nvarh,slen(repository));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(shape(dataarr,0)==ngridtot)*/
  } /*if (f2py_success) of ngridtot*/
  /* End of cleaning variable ngridtot */
  } /*if (f2py_success) of xmax*/
  /* End of cleaning variable xmax */
  } /*if (f2py_success) of xmin*/
  /* End of cleaning variable xmin */
  } /*if (f2py_success) of ymin*/
  /* End of cleaning variable ymin */
  } /*if (f2py_success) of zmax*/
  /* End of cleaning variable zmax */
  } /*if (f2py_success) of zmin*/
  /* End of cleaning variable zmin */
    STRINGFREE(repository);
  }  /*if (f2py_success) of repository*/
  /* End of cleaning variable repository */
  } /*if (f2py_success) of nvarh*/
  /* End of cleaning variable nvarh */
  if((PyObject *)capi_dataarr_tmp!=dataarr_capi) {
    Py_XDECREF(capi_dataarr_tmp); }
  }  /*if (capi_dataarr_tmp == NULL) ... else of dataarr*/
  /* End of cleaning variable dataarr */
  } /*if (f2py_success) of ymax*/
  /* End of cleaning variable ymax */
  } /*if (f2py_success) of lmax*/
  /* End of cleaning variable lmax */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of a2c_load_shared ***************************/

/*********************************** title ***********************************/
static char doc_f2py_rout_a2c_title[] = "\
title(n,nchar)\n\nWrapper for ``title``.\
\n\nParameters\n----------\n"
"n : input int\n"
"nchar : input string(len=5)";
/* extern void F_FUNC(title,TITLE)(int*,string,size_t); */
static PyObject *f2py_rout_a2c_title(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  string nchar = NULL;
  int slen(nchar);
  PyObject *nchar_capi = Py_None;
  static char *capi_kwlist[] = {"n","nchar",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:a2c.title",\
    capi_kwlist,&n_capi,&nchar_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"a2c.title() 1st argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nchar */
  slen(nchar) = 5;
  f2py_success = string_from_pyobj(&nchar,&slen(nchar),"",nchar_capi,"string_from_pyobj failed in converting 2nd argument `nchar' of a2c.title to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,nchar,slen(nchar));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(nchar);
  }  /*if (f2py_success) of nchar*/
  /* End of cleaning variable nchar */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of title ********************************/

/********************************* hilbert3d *********************************/
static char doc_f2py_rout_a2c_hilbert3d[] = "\
hilbert3d(x,y,z,order,bit_length,[npoint])\n\nWrapper for ``hilbert3d``.\
\n\nParameters\n----------\n"
"x : input rank-1 array('i') with bounds (npoint)\n"
"y : input rank-1 array('i') with bounds (npoint)\n"
"z : input rank-1 array('i') with bounds (npoint)\n"
"order : input rank-1 array('d') with bounds (npoint)\n"
"bit_length : input int\n"
"\nOther Parameters\n----------------\n"
"npoint : input int, optional\n    Default: len(x)";
/* extern void F_FUNC(hilbert3d,HILBERT3D)(int*,int*,int*,double*,int*,int*); */
static PyObject *f2py_rout_a2c_hilbert3d(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  int *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  int *z = NULL;
  npy_intp z_Dims[1] = {-1};
  const int z_Rank = 1;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  PyObject *z_capi = Py_None;
  double *order = NULL;
  npy_intp order_Dims[1] = {-1};
  const int order_Rank = 1;
  PyArrayObject *capi_order_tmp = NULL;
  int capi_order_intent = 0;
  PyObject *order_capi = Py_None;
  int bit_length = 0;
  PyObject *bit_length_capi = Py_None;
  int npoint = 0;
  PyObject *npoint_capi = Py_None;
  static char *capi_kwlist[] = {"x","y","z","order","bit_length","npoint",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|O:a2c.hilbert3d",\
    capi_kwlist,&x_capi,&y_capi,&z_capi,&order_capi,&bit_length_capi,&npoint_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable bit_length */
    f2py_success = int_from_pyobj(&bit_length,bit_length_capi,"a2c.hilbert3d() 5th argument (bit_length) can't be converted to int");
  if (f2py_success) {
  /* Processing variable x */
  ;
  capi_x_intent |= F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(NPY_INT,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 1st argument `x' of a2c.hilbert3d to C/Fortran array" );
  } else {
    x = (int *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable npoint */
  if (npoint_capi == Py_None) npoint = len(x); else
    f2py_success = int_from_pyobj(&npoint,npoint_capi,"a2c.hilbert3d() 1st keyword (npoint) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(x)>=npoint,"len(x)>=npoint","1st keyword npoint","hilbert3d:npoint=%d",npoint) {
  /* Processing variable order */
  order_Dims[0]=npoint;
  capi_order_intent |= F2PY_INTENT_IN;
  capi_order_tmp = array_from_pyobj(NPY_DOUBLE,order_Dims,order_Rank,capi_order_intent,order_capi);
  if (capi_order_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 4th argument `order' of a2c.hilbert3d to C/Fortran array" );
  } else {
    order = (double *)(PyArray_DATA(capi_order_tmp));

  /* Processing variable z */
  z_Dims[0]=npoint;
  capi_z_intent |= F2PY_INTENT_IN;
  capi_z_tmp = array_from_pyobj(NPY_INT,z_Dims,z_Rank,capi_z_intent,z_capi);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 3rd argument `z' of a2c.hilbert3d to C/Fortran array" );
  } else {
    z = (int *)(PyArray_DATA(capi_z_tmp));

  /* Processing variable y */
  y_Dims[0]=npoint;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(NPY_INT,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(a2c_error,"failed in converting 2nd argument `y' of a2c.hilbert3d to C/Fortran array" );
  } else {
    y = (int *)(PyArray_DATA(capi_y_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(x,y,z,order,&bit_length,&npoint);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_z_tmp!=z_capi) {
    Py_XDECREF(capi_z_tmp); }
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  if((PyObject *)capi_order_tmp!=order_capi) {
    Py_XDECREF(capi_order_tmp); }
  }  /*if (capi_order_tmp == NULL) ... else of order*/
  /* End of cleaning variable order */
  } /*CHECKSCALAR(len(x)>=npoint)*/
  } /*if (f2py_success) of npoint*/
  /* End of cleaning variable npoint */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  } /*if (f2py_success) of bit_length*/
  /* End of cleaning variable bit_length */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of hilbert3d ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"a2c_count",-1,{{-1}},0,(char *)F_FUNC_US(a2c_count,A2C_COUNT),(f2py_init_func)f2py_rout_a2c_a2c_count,doc_f2py_rout_a2c_a2c_count},
  {"a2c_load",-1,{{-1}},0,(char *)F_FUNC_US(a2c_load,A2C_LOAD),(f2py_init_func)f2py_rout_a2c_a2c_load,doc_f2py_rout_a2c_a2c_load},
  {"a2c_load_shared",-1,{{-1}},0,(char *)F_FUNC_US(a2c_load_shared,A2C_LOAD_SHARED),(f2py_init_func)f2py_rout_a2c_a2c_load_shared,doc_f2py_rout_a2c_a2c_load_shared},
  {"title",-1,{{-1}},0,(char *)F_FUNC(title,TITLE),(f2py_init_func)f2py_rout_a2c_title,doc_f2py_rout_a2c_title},
  {"hilbert3d",-1,{{-1}},0,(char *)F_FUNC(hilbert3d,HILBERT3D),(f2py_init_func)f2py_rout_a2c_hilbert3d,doc_f2py_rout_a2c_hilbert3d},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "a2c",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_a2c(void) {
#else
#define RETVAL
PyMODINIT_FUNC inita2c(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = a2c_module = PyModule_Create(&moduledef);
#else
  m = a2c_module = Py_InitModule("a2c", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module a2c (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'a2c' is auto-generated with f2py (version:2).\nFunctions:\n"
"  a2c_count(ngridtot,nvarh,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax)\n"
"  a2c_load(xarr,dxarr,varr,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax,ngridtot=shape(xarr,0),nvarh=shape(varr,1))\n"
"  a2c_load_shared(dataarr,repository,xmin,xmax,ymin,ymax,zmin,zmax,lmax,nvarh,ngridtot=shape(dataarr,0))\n"
"  title(n,nchar)\n"
"  hilbert3d(x,y,z,order,bit_length,npoint=len(x))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  a2c_error = PyErr_NewException ("a2c.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"a2c");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
